spring.application.name=ECommerce
spring.h2.console.enabled=true
# Use an absolute path to ensure all processes point to the same physical territory
spring.datasource.url=jdbc:h2:file:/Users/ajaydeepakgathadi/IdeaProjects/ecommerce/ecommerce;AUTO_SERVER=TRUE
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
project.images.directory=product-images